apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: nginx-deamonset
spec:
 selector:
  matchLabels:
   app: nginx-daemonset
 template:
  metadata:
   labels:
    app: nginx-daemonset
  spec:
   containers:
   - name: nginx-container
     image: nginx:alpine
   restartPolicy: Always
