---
apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  app: nginx-app
spec:
 containers:
 - name: nginx-pod
   image: nginx:latest
   ports:
   - name: nginx-port
     containerPort: 80
     protocol: TCP
    
