apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: nginx-deployment
 template:
  metadata:
   labels:
    app: nginx-deployment
  spec:
   containers:
   - name: nginx-container
     image: nginx:alpine
     ports:
     - containerPort: 80
