apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  app: nginx-pod
spec:
 containers:
 - name: nginx-container
   image: nginx:alpine
   ports:
   - containerPort: 80
     protocol: TCP
     
