apiVersion: apps/v1
kind: Deployment
metadata:
 name: recreate-deployment
spec:
 replicas: 5
 selector:
  matchLabels:
   app: nginx-recreate
 strategy:
  type: Recreate
 template:
  metadata:
   name: nginx-pod
   labels:
    app: nginx-recreate
  spec:
   containers:
   - name: nginx-container
     image: nginx:1-alpine
     imagePullPolicy: IfNotPresent
     ports:
     - containerPort: 80
   restartPolicy: Always
