apiVersion: apps/v1
kind: Deployment
metadata:
 name: ninja-game
 labels:
  app: ninja-game
  version: v1
spec:
 replicas: 4
 selector:
  matchLabels:
   app: ninja-game
   version: v1
 template:
  metadata:
   name: ninja-game-pod
   labels:
    app: ninja-game
    version: v1
  spec:
   containers:
   - name: v1-container
     image: vrnvav123/ninja-game:v1
     imagePullPolicy: Always
     ports:
     - containerPort: 80
