---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
spec:
 replicas: 5
 selector:
  matchLabels:
   app: nginx-deploy
 template:
  metadata:
   labels:
    app: nginx-deploy
  spec:
   containers:
   - name: nginx-container
     image: nginx:alpine
     ports:
     - containerPort: 80
       protocol: TCP
     imagePullPolicy: IfNotPresent
     volumeMounts:
     - name: shared-data
       mountPath: /usr/share/nginx/html/
   volumes:
   - name: shared-data
     hostPath:
      path: /tmp/html/
      type: Directory
